### ISSUE TITLE
uget not start on docker w/raspberry pi 4

### ISSUE THREAD

**Issue by Stephen988** [djaydev/docker-uget#1]
Hi, I have installed uget container on openmediavault x86 and work perfectly, but the same not work on my raspberry pi 4 with same omv configuration, also port are mapped for pi on my router.

**Comment by djaydev** [comment]
Hi Stephen988,
The container only works on x86 and x64 systems.  The raspberrypi 4 supports ARM based images only.  I can't provide an ARM image for uget because the baseimage comes in x86/x64 only.

**Comment by Stephen988** [comment]
> Hi Stephen988,
> The container only works on x86 and x64 systems. The raspberrypi 4 supports ARM based images only. I can't provide an ARM image for uget because the baseimage comes in x86/x64 only.
Hi @djaydev how can I use in alternative? I need on raspberry a good download manager (not torrent).
